owner: vanyakosmos
repo: zakaz-uptime

sites: []

status-website:
  baseUrl: /zakaz-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Zazaz.ua** Uptime"
  introMessage: This is a status page which uses **real-time** data from our [Github repository](https://github.com/vanyakosmos/zakaz-uptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 31 2 *"
  responseTime: "0 0 31 2 *"
  staticSite: "0 0 31 2 *"
  summary: "0 0 31 2 *"
  updateTemplate: "0 0 31 2 *"
  updates: "0 0 31 2 *"
  uptime: "0 0 31 2 *"
