owner: vanyakosmos
repo: zakaz-uptime

sites:
  - name: Main
    url: https://zakaz.ua
  - name: Metro
    url: https://metro.zakaz.ua
  - name: Auchan
    url: https://auchan.zakaz.ua
  - name: Novus
    url: https://novus.zakaz.ua
  - name: CityMarket
    url: https://citymarket.zakaz.ua
  - name: Cosmos
    url: https://cosmos.zakaz.ua
  - name: Ekomarket
    url: https://ekomarket.zakaz.ua
  - name: Megamarket
    url: https://megamarket.zakaz.ua
  - name: Pchelka
    url: https://pchelka.zakaz.ua
  - name: Stolychiy
    url: https://stolychyi.zakaz.ua
  - name: Tavria V
    url: https://tavriav.zakaz.ua
  - name: UltraMarket
    url: https://ultramarket.zakaz.ua
  - name: Varus
    url: https://varus.zakaz.ua
  - name: Vostorg
    url: https://vostorg.zakaz.ua
  - name: Metro MD
    url: https://metro.zakaz.md
  - name: Stores API - UA
    url: https://stores-api.zakaz.ua
  - name: Stores API - MD
    url: https://stores-api.zakaz.md
  - name: Stores API - TEST
    url: https://stores-api.test.zakaz.ua

status-website:
  baseUrl: /zakaz-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Zazaz.ua** Uptime"
  introMessage: This is a status page which uses **real-time** data from our [Github repository](https://github.com/vanyakosmos/zakaz-uptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/2 * * * *"
