owner: vanyakosmos
repo: zakaz-uptime

sites:
  - name: Main
    url: https://zakaz.ua
  - name: Metro
    url: https://metro.zakaz.ua
  - name: Auchan
    url: https://auchan.zakaz.ua
  - name: Novus
    url: https://novus.zakaz.ua
  - name: Stores API - UA
    url: https://stores-api.zakaz.ua
  - name: Stores API - RU
    url: https://stores-api.zakaz.ru
  - name: Stores API - MD
    url: https://stores-api.zakaz.md
  - name: Stores API - UZ
    url: https://stores-api.zakaz.uz
  - name: Stores API - TEST
    url: https://stores-api.test.zakaz.ua

status-website:
  baseUrl: /zakaz-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Zazaz.ua** Uptime"
  introMessage: This is a status page which uses **real-time** data from our [Github repository](https://github.com/vanyakosmos/zakaz-uptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
